name: Release

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"
          check-latest: true
      - run: ./gradlew clean build jib
        env:
          GITHUB_REF_NAME: ${{ github.GITHUB_REF_NAME }}
          GITHUB_PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}